# Change these first
owner: jrmi # Your GitHub username
repo: airboardgame_upptime # Your GitHub repository name

assignees: # Users to assign downtime issues (optional)
  - jrmi

# Add your sites here
sites:
  - name: Airboardgame
    url: https://airboardgame.net
  - name: Ricochet
    url: https://public.jeremiez.net/ricochet/store/game?fields=_id%2Cboard%2Cowner
    headers:
      - "Origin: https://airboardgame.net"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /airboardgame_upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Airboardgame
  introTitle: "**Upptime** for airboardgame."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
